export const SCALING_CONSTANTS = {
  MIN_INSTANCES: 1,
  MAX_INSTANCES: 100,
  VERTICAL_SCALING_THRESHOLD: 0.8,
  HORIZONTAL_SCALING_THRESHOLD: 0.9,
  COST_PER_INSTANCE_HOUR: 0.1,
  LATENCY_TARGET_MS: 50
};

export const WORKLOAD_PATTERNS = {
  STEADY: 'steady',
  SPIKY: 'spiky',
  UNPREDICTABLE: 'unpredictable'
};