"""Initial migration

Revision ID: 0001
Revises: 
Create Date: 2025-11-08 18:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app.schemas.logs import LogLevel

# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    
    op.create_table('log_entries',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
        sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='loglevel'), nullable=True),
        sa.Column('message', sa.Text(), nullable=True),
        sa.Column('service', sa.String(), nullable=True),
        sa.Column('tenant_id', sa.String(), nullable=True),
        sa.Column('trace_id', sa.String(), nullable=True),
        sa.Column('span_id', sa.String(), nullable=True),
        sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_index('idx_log_entries_level_timestamp', 'log_entries', ['level', 'timestamp'], unique=False)
    op.create_index('idx_log_entries_service_timestamp', 'log_entries', ['service', 'timestamp'], unique=False)
    op.create_index('idx_log_entries_tenant_timestamp', 'log_entries', ['tenant_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_log_entries_service'), 'log_entries', ['service'], unique=False)
    op.create_index(op.f('ix_log_entries_tenant_id'), 'log_entries', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_log_entries_timestamp'), 'log_entries', ['timestamp'], unique=False)
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_index(op.f('ix_log_entries_timestamp'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_tenant_id'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_service'), table_name='log_entries')
    op.drop_index('idx_log_entries_tenant_timestamp', table_name='log_entries')
    op.drop_index('idx_log_entries_service_timestamp', table_name='log_entries')
    op.drop_index('idx_log_entries_level_timestamp', table_name='log_entries')
    op.drop_table('log_entries')
    op.drop_table('tenants')
    # ### end Alembic commands ###